// Brand list sourced from the All Brands reference HTML

export const allBrandNames = [
  "@need Marketing",
  "10Com",
  "16 Handles",
  "1st Family Dental",
  "1st Lake Properties",
  "1st Source Bank",
  "2060 Digital",
  "220 Marketing",
  "222 Digital Marketing",
  "24 seven talent",
  "2A Marketing",
  "2D SEO",
  "30 Lines",
  "4 Rivers Smokehouse",
  "44i, Inc.",
  "4Front Credit Union",
  "829 Studios",
  "911 Restoration",
  "961 Interactive",
  "A Wireless",
  "A.R. Building Company",
  "A+ Home Furnishings",
  "a1garage",
  "Aaron's, Inc",
  "Abbey Residential - Single Domain Client",
  "ABC Liquors Inc.",
  "ABC Local, LLC",
  "Abstrakt Marketing Group, L.L.C.",
  "Abundant Designs LLC",
  "Academy, Ltd. d/b/a Academy Sports + Outdoors",
  "Acadia",
  "Acadia Realty",
  "Access Storage Now - Main Office",
  "acehandyman_swflorida",
  "Acme Fresh Market",
  "ACME Markets",
  "ACNB Bank",
  "Act!on Marketing",
  "ActiveData Mobile",
  "Adams and Reese LLP",
  "Adams Multi Media",
  "AdCellerant",
  "Addus Homecare",
  "Adecco Group NA",
  "Adept Marketing",
  "ADP",
  "Ads Helper",
  "Ads Next",
  "ADSC Specialists",
  "Advance Auto Parts",
  "Advanced Drainage Systems, Inc.",
  "Advantage Marketing Inc.",
  "Advent Trinity",
  "Advertising Specialty Institute",
  "advice media",
  "Aerie",
  "Affinitiv",
  "Affinity Federal Credit Union",
  "Affordable Home Furnishings",
  "Affordable SEO FL",
  "AG Georgia Farm Credit",
  "Ag Resource Management",
  "Agency FIFTY3",
  "Agency Media Solutions",
  "Agent Elite, Inc.",
  "AgeWell Solvere Living",
  "AgSouth Farm Credit",
  "Ahold U.S.A., Inc.",
  "Aimbridge Hospitality",
  "AION Management",
  "AION Partners, LLC",
  "AIT Worldwide Logistics",
  "Alabama Ag Credit",
  "Alabama Credit Union",
  "Alamo",
  "Alberta Motor Association",
  "Albertsons",
  "Alcool NB Liquor",
  "Aletheia Digital",
  "Alexa Digital",
  "Alexander McQueen",
  "All Family Dental and Braces",
  "All In Adventures",
  "Allegiant Digital Marketing",
  "Allstate",
  "ALO, LLC",
  "Alpha 1 Marketing",
  "Alpha Fit",
  "AlphaGraphics Inc.",
  "Alpine Bank",
  "Altom Consulting",
  "Altura Credit Union",
  "AM Retail Group, Inc.",
  "Amada Senior Care",
  "Amadeus",
  "Ambercare",
  "AMC - Acacia Capital",
  "AMC - Jackson Square Properties",
  "American Airlines Federal Credit Union",
  "American Bank",
  "American Creative",
  "American Eagle Outfitters",
  "American Furniture Warehouse",
  "American National Bank of Texas",
  "American Rental Home Furnishings",
  "americaneagle.com",
  "AmeriCU Credit Union",
  "Ameriprise",
  "AMF Bowling Centers, Inc.",
  "Amica Senior Lifestyles Inc",
  "Amoco Federal Credit Union",
  "Amplifon",
  "Amplus Agency",
  "Amramp",
  "AMSOIL, INC.",
  "ANB Bank",
  "Andersen Windows",
  "Anderson Brothers Bank",
  "Angel Reyes - Reyes Browne Law Firm",
  "Ann Taylor",
  "Ansira Partners II, LLC",
  "Anthony & Sylvan Pools",
  "ANTONIO PUIG S.A",
  "Anywhere Integrated Services",
  "Apex Media Solutions, LLC",
  "aplusgaragedoor",
  "Apotheca, Inc.",
  "Apotheco Pharmacy",
  "Apple",
  "Apple Montessori Schools",
  "Apt CoWork",
  "Aptive Environmental, LLC",
  "aquariuswaterconditioning",
  "aquasystems",
  "AR Sync",
  "Arcadia Home Care & Staffing",
  "Architectural Ceramics",
  "ARI - R.E. Carroll Management Company - Single Domain",
  "Ariat International, Inc.",
  "Army Recruiting c/o Carahsoft",
  "Arona Corporation",
  "Around29",
  "Arthur J Gallagher & Co.",
  "Ascent Digital",
  "Ashton Woods Homes",
  "Associa",
  "Associated Credit Union of Texas",
  "Associated Wholesale Grocers (AWG)",
  "Assured Automotive",
  "At Home",
  "ATG Entertainment Limited",
  "Atlantic Auto Group",
  "Atlantic Union Bank",
  "Atlas",
  "Atmosphere",
  "ATW",
  "AtWork Group",
  "Auberge Resorts, LLC",
  "Auntie Anne's",
  "Authentic Restaurant Brands",
  "Auto Select Group LLC",
  "Autobell",
  "Autoshop Solutions",
  "Autowash @ Meadow Pointe",
  "AutoZone",
  "Avalon Flooring",
  "Aveda Corporation",
  "Avelient",
  "Averitt Express",
  "Aviation Institute of Maintenance",
  "avid Hotels",
  "Ayerco",
  "Azura Vascular Care",
  "B & M Management Company LLC",
  "B3 Studios, LLC",
  "Bach To Rock",
  "Backus Marketing & Design",
  "Baers Furniture Co Inc",
  "Bahama Breeze",
  "Baker's",
  "Balcom Agency",
  "Balenciaga",
  "Ballantine Communications (BLNT)",
  "Banc of California",
  "Banfield Pet Hospitals",
  "Bank of Hawaii",
  "Bank of Hope",
  "Bank of Missouri",
  "Bank OZK",
  "Bank7 Corp.",
  "Bankers Life",
  "BankRI",
  "Banner Bank",
  "Barcelona Wine Bar",
  "Barnum Financial",
  "Barro's Pizza",
  "Barry's Bootcamp LLC",
  "Bartlesville Radio",
  "Bartlett Funeral Home and Cremation",
  "Basement Systems",
  "Baskin-Robbins",
  "Bass Pro Shops",
  "BayPort Credit Union",
  "BB Living",
  "BCC Interactive",
  "BDG Dental Services",
  "Be Found Online",
  "Beacon Credit Union",
  "Beacon Health System",
  "Bealls, Inc.",
  "Beals Cunningham Strategic Services",
  "Bear Fox Marketing",
  "Bearing Insurance",
  "Beazer Homes",
  "Belk",
  "Bell Bank",
  "Bell Canada",
  "Bellco Credit Union",
  "Belle Tire",
  "Belmont Village",
  "Beltone Audiology and Hearing Aids",
  "Ben & Jerry's",
  "Benchmark Senior Living",
  "BenchMark Website Design",
  "Berkshire Group",
  "Bertucci's Restaurant",
  "Bessemer Trust",
  "Best Buy",
  "Best Buy Canada",
  "Best Western",
  "Better Health Group Services, Inc",
  "BHI Residential Long Term Corporation",
  "Bibibop Asian Grill",
  "Bickford Senior Living",
  "Bierman Autism Centers",
  "Big Chicken",
  "Big Red",
  "Big Swell",
  "Binny's Beverage Depot",
  "BizIQ",
  "Blaze Pizza LLC",
  "Blick Art Materials",
  "Blue Foundry Bank",
  "Blue Interactive Agency",
  "Blue Ridge Bank",
  "Blue Ridge Communications",
  "Blue Zone Marketing",
  "Bluebird Creative Company",
  "BlueFoot",
  "Bluegreen Vacations Corporation",
  "Blueprint.Inc",
  "Bluestone Lane",
  "Bob Digital Marketing",
  "Bob's Discount Furniture",
  "Bobcat",
  "Body Fit Training",
  "BODY20",
  "BODYBAR Pilates",
  "Bojangles' Restaurants",
  "BOKF, N.A.",
  "Bolton & Menk, Inc.",
  "Bond Vet",
  "Bonefish Grill",
  "Bonneville International",
  "Bonobos",
  "Booyah Online Advertising",
  "Boqueria",
  "BOSS Marketing Group",
  "BOSS Tenders, Dogs & Custard",
  "Boston's Pizza",
  "Bottega Veneta",
  "Bottom Line Black Marketing",
  "Boyd Autobody",
  "Boyd Gaming Corporation",
  "BPL Plasma",
  "Bradley Arant Boult Cummings",
  "Branded Internet Marketing Agency LLC",
  "BRAVO Cucina Italiana",
  "Brawn Media",
  "Breitling Boutique",
  "Breitling SA",
  "Brew Culture, LLC",
  "Bright Horizons Family Solutions LLC",
  "Brightpath Early Learning Inc",
  "Brightway Insurance",
  "Brillity Digital",
  "Brio Tuscan Grille",
  "British Swim School",
  "Brixmor",
  "Brixx",
  "Broad Leaf Marketing",
  "Bronson Healthcare",
  "Brookdale Senior Living",
  "Brookline Bank",
  "Brooks Brothers",
  "Brownstein Hyatt Farber Schreck",
  "Bruegger's Bagels",
  "Brundage Management Co Inc",
  "BSPE Legal Marketing",
  "Bubba Gump Shrimp Co"
] as const
