import { IMAGES } from './images'

export const categories = [
  { name: 'Agriculture &', name2: 'Industry', icon: IMAGES.categories[0] },
  { name: 'Arts &', name2: 'Entertainment', icon: IMAGES.categories[1] },
  { name: 'Automotive', icon: IMAGES.categories[2] },
  { name: 'Beauty', icon: IMAGES.categories[3] },
  { name: 'Business Services', icon: IMAGES.categories[4] },
  { name: 'Contractors', icon: IMAGES.categories[5] },
  { name: 'Education', icon: IMAGES.categories[6] },
  { name: 'Family & Community', icon: IMAGES.categories[7] },
  { name: 'Financial Services', icon: IMAGES.categories[8] },
  { name: 'Food & Dining', icon: IMAGES.categories[9] },
  { name: 'Government', icon: IMAGES.categories[10] },
  { name: 'Health', icon: IMAGES.categories[11] },
  { name: 'Home & Garden', icon: IMAGES.categories[12] },
  { name: 'Insurance', icon: IMAGES.categories[13] },
  { name: 'Legal', icon: IMAGES.categories[14] },
  { name: 'Moving & Transport', icon: IMAGES.categories[15] },
  { name: 'Pets', icon: IMAGES.categories[16] },
  { name: 'Real Estate', icon: IMAGES.categories[17] },
  { name: 'Shopping', icon: IMAGES.categories[18] },
  { name: 'Sports & Recreation', icon: IMAGES.categories[19] },
  { name: 'Technology', icon: IMAGES.categories[20] },
  { name: 'Telecoms', icon: IMAGES.categories[21] },
  { name: 'Travel', icon: IMAGES.categories[22] },
  { name: 'Other', icon: IMAGES.categories[23] },
]

export const brands = [
  {
    name: 'Western Union',
    locations: '556,375 locations',
    category: 'Financial Services',
    rating: 4.5,
    logo: IMAGES.brands.westernUnion,
  },
  {
    name: "McDonald's",
    locations: '13,445 locations',
    category: 'Food & Dining',
    rating: 4.5,
    logo: IMAGES.brands.mcdonalds,
  },
  {
    name: 'Starbucks',
    locations: '11,750 locations',
    category: 'Food & Dining',
    rating: 4.5,
    logo: IMAGES.brands.starbucks,
  },
  {
    name: "Freddy's Frozen Custard & Steakburgers",
    locations: '4,273 locations',
    category: 'Food & Dining',
    rating: 4.5,
    logo: IMAGES.brands.freddys,
  },
  {
    name: 'Advance Auto Parts',
    locations: '6,752 locations',
    category: 'Automotive',
    rating: 4.5,
    logo: IMAGES.brands.advanceAuto,
  },
  {
    name: 'LensCrafters',
    locations: '6,752 locations',
    category: 'Health',
    rating: 4.5,
    logo: IMAGES.brands.lensCrafters,
  },
  {
    name: 'Advance Auto Parts',
    locations: '6,752 locations',
    category: 'Automotive',
    rating: 4.5,
    logo: IMAGES.brands.advanceAuto,
  },
  {
    name: "Freddy's Frozen Custard & Steakburgers",
    locations: '4,273 locations',
    category: 'Food & Dining',
    rating: 4.5,
    logo: IMAGES.brands.freddys,
  },
  {
    name: 'LensCrafters',
    locations: '6,752 locations',
    category: 'Health',
    rating: 4.5,
    logo: IMAGES.brands.lensCrafters,
  },
]

