// Image paths - Update these paths to match your image filenames in the public folder
export const IMAGES = {
  logo: "/images/icons/logo.svg",
  yext_logo: "/images/brands/yext_logo.svg",
  heroBackground: "/images/illustrations/hero-background.jpg",
  hero: "/images/illustrations/hero.webp",
  emptyDone: "/images/illustrations/empty-done.svg",
  noResult: "/images/illustrations/no_result.svg",
  tag: "/images/icons/tag.svg",
  stars: "/images/icons/Stars.svg",
  star_single: "/images/icons/star_single.svg",
  verified_icon: "/images/icons/verified-icon.svg",
  warning_icon: "/images/icons/warning-icon.svg",
  check: "/images/icons/check.svg",
  arrow: "/images/icons/arrow.svg",
  chevron: "/images/icons/chevron.svg",
  home: "/images/icons/home.svg",
  filter: "/images/icons/filter.svg",
  facebook: "/images/icons/facebook.svg",
  facebook_color: "/images/icons/facebook_color.svg",
  instagram: "/images/icons/instagram.svg",
  instagram_color: "/images/icons/insta_color.svg",
  twitter: "/images/icons/twitter.svg",
  linkedin: "/images/icons/linkedin.svg",
  youtube: "/images/icons/youtube.svg",
  search: "/images/icons/search.svg",
  sparkle: "/images/icons/sparkle.svg",
  location: "/images/icons/location.svg",
  phone: "/images/icons/phone.svg",
  external: "/images/icons/external.svg",
  link: "/images/icons/link.svg",
  lock: "/images/icons/lock.svg",
  google_location: "/images/illustrations/google_location.png",
  all_brands: "/images/categories/all_brands.svg",
  brands: {
    // Brand logos for homepage
    starbucks: "/images/brands/starbucks.svg",
    westernUnion: "/images/brands/western-union.svg",
    freddys: "/images/brands/freddys.svg",
    advanceAuto: "/images/brands/advance-auto.svg",
    lensCrafters: "/images/brands/lenscrafters.svg",
    // Brand logos for brand pages
    all: "/images/brands/placeholder.svg",
    tacoBell: "/images/brands/taco-bell.svg",
    baskinRobbins: "/images/brands/BR.png",
  },
  categories: [
    "/images/categories/agriculture.svg",
    "/images/categories/arts-entertainment.svg",
    "/images/categories/automotive.svg",
    "/images/categories/beauty.svg",
    "/images/categories/business-services.svg",
    "/images/categories/contractors.svg",
    "/images/categories/education.svg",
    "/images/categories/family-community.svg",
    "/images/categories/financial-services.svg",
    "/images/categories/food-dining.svg",
    "/images/categories/government.svg",
    "/images/categories/health.svg",
    "/images/categories/home-garden.svg",
    "/images/categories/insurance.svg",
    "/images/categories/legal.svg",
    "/images/categories/moving-transport.svg",
    "/images/categories/pets.svg",
    "/images/categories/real-estate.svg",
    "/images/categories/shopping.svg",
    "/images/categories/sports-recreation.svg",
    "/images/categories/technology.svg",
    "/images/categories/telecoms.svg",
    "/images/categories/travel.svg",
    "/images/categories/other.svg",
  ],
} as const
