export type SearchResult = {
  slug: string
  name: string
  category: string
  rating: number
  reviewCount: number
  address: string
  openText: string
  lat: number
  lng: number
  isOpen: boolean
  claimed: boolean
  image?: string
  imageUrl?: string // Matches business hero image
  phone?: string
  hours?: string
}

export const searchResults: SearchResult[] = [
  {
    slug: 'taco-bell-albany-central-ave',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.2,
    reviewCount: 862,
    address: '123 Main Street, Albany, NY',
    openText: 'Open now · Closes 1:00 AM',
    lat: 42.6526,
    lng: -73.7562,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0123',
    hours: '10:00 AM - 1:00 AM',
  },
  {
    slug: 'taco-bell-albany-washington',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.5,
    reviewCount: 523,
    address: '456 Washington Ave, Albany, NY',
    openText: 'Open now · Closes 12:00 AM',
    lat: 42.6589,
    lng: -73.7483,
    isOpen: true,
    claimed: false,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0124',
    hours: '9:00 AM - 12:00 AM',
  },
  {
    slug: 'taco-bell-albany-madison',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.0,
    reviewCount: 312,
    address: '789 Madison Ave, Albany, NY',
    openText: 'Closed · Opens 10:00 AM',
    lat: 42.6451,
    lng: -73.7634,
    isOpen: false,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0125',
    hours: '10:00 AM - 11:00 PM',
  },
  {
    slug: 'taco-bell-albany-pearl',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.3,
    reviewCount: 445,
    address: '321 Pearl Street, Albany, NY',
    openText: 'Open now · Closes 11:00 PM',
    lat: 42.6510,
    lng: -73.7510,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0126',
    hours: '10:00 AM - 11:00 PM',
  },
  {
    slug: 'taco-bell-albany-lark',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.1,
    reviewCount: 389,
    address: '567 Lark Street, Albany, NY',
    openText: 'Open now · Closes 12:30 AM',
    lat: 42.6530,
    lng: -73.7590,
    isOpen: true,
    claimed: false,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0127',
    hours: '9:00 AM - 12:30 AM',
  },
  {
    slug: 'taco-bell-albany-western',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.4,
    reviewCount: 521,
    address: '890 Western Avenue, Albany, NY',
    openText: 'Open now · Closes 1:00 AM',
    lat: 42.6600,
    lng: -73.7650,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0128',
    hours: '10:00 AM - 1:00 AM',
  },
  {
    slug: 'taco-bell-albany-central',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.2,
    reviewCount: 678,
    address: '234 Central Avenue, Albany, NY',
    openText: 'Open now · Closes 11:30 PM',
    lat: 42.6470,
    lng: -73.7570,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0129',
    hours: '10:30 AM - 11:30 PM',
  },
  {
    slug: 'taco-bell-albany-colonie',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.6,
    reviewCount: 892,
    address: '145 Wolf Road, Colonie, NY',
    openText: 'Open now · Closes 12:00 AM',
    lat: 42.7200,
    lng: -73.8200,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0130',
    hours: '9:00 AM - 12:00 AM',
  },
  {
    slug: 'taco-bell-albany-troy',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.3,
    reviewCount: 567,
    address: '678 Hoosick Street, Troy, NY',
    openText: 'Open now · Closes 11:00 PM',
    lat: 42.7300,
    lng: -73.6900,
    isOpen: true,
    claimed: false,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0131',
    hours: '10:00 AM - 11:00 PM',
  },
  {
    slug: 'taco-bell-albany-schenectady',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.1,
    reviewCount: 423,
    address: '789 State Street, Schenectady, NY',
    openText: 'Closed · Opens 9:00 AM',
    lat: 42.8100,
    lng: -73.9400,
    isOpen: false,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0132',
    hours: '9:00 AM - 10:00 PM',
  },
  {
    slug: 'taco-bell-albany-guilderland',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.5,
    reviewCount: 734,
    address: '234 Western Avenue, Guilderland, NY',
    openText: 'Open now · Closes 12:00 AM',
    lat: 42.7000,
    lng: -73.9000,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0133',
    hours: '9:30 AM - 12:00 AM',
  },
  {
    slug: 'taco-bell-albany-clifton-park',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.4,
    reviewCount: 612,
    address: '456 Route 9, Clifton Park, NY',
    openText: 'Open now · Closes 11:00 PM',
    lat: 42.8500,
    lng: -73.7800,
    isOpen: true,
    claimed: false,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0134',
    hours: '10:00 AM - 11:00 PM',
  },
  {
    slug: 'taco-bell-albany-latham',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.2,
    reviewCount: 489,
    address: '567 New Loudon Road, Latham, NY',
    openText: 'Open now · Closes 11:30 PM',
    lat: 42.7500,
    lng: -73.7500,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0135',
    hours: '10:00 AM - 11:30 PM',
  },
  {
    slug: 'taco-bell-albany-delmar',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.3,
    reviewCount: 356,
    address: '123 Delaware Avenue, Delmar, NY',
    openText: 'Open now · Closes 10:00 PM',
    lat: 42.6200,
    lng: -73.8300,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0136',
    hours: '10:00 AM - 10:00 PM',
  },
  {
    slug: 'taco-bell-albany-east-greenbush',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.0,
    reviewCount: 278,
    address: '789 Columbia Turnpike, East Greenbush, NY',
    openText: 'Closed · Opens 8:00 AM',
    lat: 42.5900,
    lng: -73.7000,
    isOpen: false,
    claimed: false,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0137',
    hours: '8:00 AM - 9:00 PM',
  },
  {
    slug: 'taco-bell-albany-watervliet',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.1,
    reviewCount: 334,
    address: '234 19th Street, Watervliet, NY',
    openText: 'Open now · Closes 11:00 PM',
    lat: 42.7100,
    lng: -73.7000,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0138',
    hours: '10:00 AM - 11:00 PM',
  },
  {
    slug: 'taco-bell-albany-cohoes',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.2,
    reviewCount: 401,
    address: '456 Remsen Street, Cohoes, NY',
    openText: 'Open now · Closes 10:30 PM',
    lat: 42.7700,
    lng: -73.7000,
    isOpen: true,
    claimed: false,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0139',
    hours: '10:00 AM - 10:30 PM',
  },
  {
    slug: 'taco-bell-albany-ballston-spa',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.4,
    reviewCount: 523,
    address: '789 Route 50, Ballston Spa, NY',
    openText: 'Open now · Closes 11:00 PM',
    lat: 43.0000,
    lng: -73.8500,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0140',
    hours: '9:00 AM - 11:00 PM',
  },
  {
    slug: 'taco-bell-albany-saratoga',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.5,
    reviewCount: 645,
    address: '123 Broadway, Saratoga Springs, NY',
    openText: 'Open now · Closes 12:00 AM',
    lat: 43.0800,
    lng: -73.7800,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0141',
    hours: '9:00 AM - 12:00 AM',
  },
  {
    slug: 'taco-bell-albany-glens-falls',
    name: 'Taco Bell',
    category: 'Food & Dining',
    rating: 4.3,
    reviewCount: 512,
    address: '456 Glen Street, Glens Falls, NY',
    openText: 'Open now · Closes 11:00 PM',
    lat: 43.3100,
    lng: -73.6400,
    isOpen: true,
    claimed: false,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(518) 555-0142',
    hours: '10:00 AM - 11:00 PM',
  },
  {
    slug: 'starbucks-georgetown',
    name: 'Starbucks',
    category: 'Coffee & Tea',
    rating: 4.6,
    reviewCount: 412,
    address: '2145 M Street NW, Washington, DC',
    openText: 'Open now · Closes 10:00 PM',
    lat: 38.9051,
    lng: -77.0470,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(202) 555-0126',
    hours: '6:00 AM - 10:00 PM',
  },
  {
    slug: 'mcdonalds-clarendon',
    name: "McDonald's",
    category: 'Burgers',
    rating: 4.1,
    reviewCount: 1180,
    address: '3100 Wilson Blvd, Arlington, VA',
    openText: 'Open now · 24 hours',
    lat: 38.8867,
    lng: -77.0947,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(703) 555-0127',
    hours: '24 hours',
  },
  {
    slug: 'freddys-ballston',
    name: "Freddy's",
    category: 'Burgers',
    rating: 4.4,
    reviewCount: 536,
    address: '4238 Wilson Blvd, Arlington, VA',
    openText: 'Open now · Closes 11:00 PM',
    lat: 38.8815,
    lng: -77.1115,
    isOpen: true,
    claimed: false,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(703) 555-0128',
    hours: '10:30 AM - 11:00 PM',
  },
  {
    slug: 'chipotle-rosslyn',
    name: 'Chipotle',
    category: 'Mexican',
    rating: 4.0,
    reviewCount: 674,
    address: '1701 N Lynn St, Arlington, VA',
    openText: 'Open now · Closes 10:00 PM',
    lat: 38.8965,
    lng: -77.0712,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(703) 555-0129',
    hours: '10:45 AM - 10:00 PM',
  },
  {
    slug: 'sweetgreen-capitol-hill',
    name: 'sweetgreen',
    category: 'Healthy',
    rating: 4.5,
    reviewCount: 289,
    address: '600 Pennsylvania Ave SE, Washington, DC',
    openText: 'Open now · Closes 9:00 PM',
    lat: 38.8869,
    lng: -76.9950,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(202) 555-0130',
    hours: '10:30 AM - 9:00 PM',
  },
  {
    slug: 'shake-shack-georgetown',
    name: 'Shake Shack',
    category: 'Burgers',
    rating: 4.3,
    reviewCount: 903,
    address: '800 New Hampshire Ave NW, Washington, DC',
    openText: 'Open now · Closes 11:30 PM',
    lat: 38.9048,
    lng: -77.0554,
    isOpen: true,
    claimed: false,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(202) 555-0131',
    hours: '11:00 AM - 11:30 PM',
  },
  {
    slug: 'five-guys-dupont',
    name: 'Five Guys',
    category: 'Burgers',
    rating: 4.2,
    reviewCount: 745,
    address: '1211 Connecticut Ave NW, Washington, DC',
    openText: 'Open now · Closes 10:00 PM',
    lat: 38.9097,
    lng: -77.0431,
    isOpen: true,
    claimed: true,
    image: '/images/illustrations/hero-background.jpg',
    phone: '(202) 555-0132',
    hours: '11:00 AM - 10:00 PM',
  },
]
